export const transcriptData = [
         {
           courseCode: "CCST 9017",
           grade: "A",
           courseName: "Game Theory",
           isPostGrad: false,
         },
         {
           courseCode: "CUND 9003",
           grade: "A-",
           courseName: "Cantonese",
           isPostGrad: false,
         },
         {
           courseCode: "ENGG 1300",
           grade: "A-",
           courseName: "Mechanical Physiscs",
           isPostGrad: false,
         },
         {
           courseCode: "ENGG 1320",
           grade: "B+",
           courseName: "Entrepreneurship",
           isPostGrad: false,
         },
         {
           courseCode: "ENGG 1330",
           grade: "A+",
           courseName: "Python",
           isPostGrad: false,
         },
         {
           courseCode: "MATH 1853",
           grade: "A+",
           courseName: "Linear Algebra & Probabilities",
           isPostGrad: false,
         },
         {
           courseCode: "CAES 1000",
           grade: "A-",
           courseName: "English",
           isPostGrad: false,
         },
         {
           courseCode: "CCCH 9001",
           grade: "A-",
           courseName: "Chinese Architecture",
           isPostGrad: false,
         },
         {
           courseCode: "ENGG 1310",
           grade: "A+",
           courseName: "Electrical Engineering",
           isPostGrad: false,
         },
         {
           courseCode: "ENGG 1340",
           grade: "A+",
           courseName: "C++ and Programming Tools",
           isPostGrad: false,
         },
         {
           courseCode: "MATH 1851",
           grade: "A+",
           courseName: "Calculus and ODE",
           isPostGrad: false,
         },
         {
           courseCode: "CCST 9073",
           grade: "Pass",
           courseName: "Emotion, Cognition and Brain",
           isPostGrad: false,
         },
         {
           courseCode: "COMP 2121",
           grade: "A+",
           courseName: "Discrete Mathematics",
           isPostGrad: false,
         },
         {
           courseCode: "COMP 2396",
           grade: "A+",
           courseName: "JAVA & OOP",
           isPostGrad: false,
         },
         {
           courseCode: "MATH 2101",
           grade: "A-",
           courseName: "Linear Algebra",
           isPostGrad: false,
         },
         {
           courseCode: "MATH 2211",
           grade: "A",
           courseName: "Multivariate Calculus",
           isPostGrad: false,
         },
         {
           courseCode: "STAT 2601",
           grade: "A+",
           courseName: "Probabilities and Statistics 1",
           isPostGrad: false,
         },
         {
           courseCode: "COMP 2119",
           grade: "A+",
           courseName: "Intro to Algorithms & Data Structure",
           isPostGrad: false,
         },
         {
           courseCode: "COMP 2120",
           grade: "A+",
           courseName: "Computer Organization",
           isPostGrad: false,
         },
         {
           courseCode: "COMP 3250",
           grade: "A",
           courseName: "Advanced Design & Analysis of Algorithms",
           isPostGrad: false,
         },
         {
           courseCode: "COMP 7309",
           grade: "A-",
           courseName: "Quantum Computing and AI",
           isPostGrad: true,
         },
         {
           courseCode: "MATH 2241",
           grade: "A+",
           courseName: "Intro to Mathematical Analysis",
           isPostGrad: false,
         },
         {
           courseCode: "STAT 2602",
           grade: "A+",
           courseName: "Probabilities and Statistics 2",
           isPostGrad: false,
         },
       ];

export const cGPA = "4.05";